### ISSUE TITLE
项目中没有关于prometheus-k8s的statefulset manifests

### ISSUE THREAD

**Issue by ynhao** [chinaboy007/kube-prometheus#2]
您好，我在您的项目中没有找到关于prometheus-k8s的statefulset manifests，那么monitoring名称空间的prometheus-k8s-0和prometheus-k8s-1是由谁控制的呢，如果我要更改配置，应该怎么办呢？

**Comment by chinaboy007** [comment]
kubectl get sts prometheus-k8s -n monitoring
