### ISSUE TITLE
数据持久化中执行kubectl apply  -f prometheus-prometheus.yaml 没生效

### ISSUE THREAD

**Issue by monkxueit** [chinaboy007/kube-prometheus#6]
在kube-prometheus/manifests/add/nfs-client/install中
persist(){
kubectl apply  -f grafana-pvc.yaml
kubectl delete -f grafana-deployment.yaml
kubectl apply  -f grafana-deployment.yaml
kubectl delete -f prometheus-prometheus.yaml
kubectl apply  -f prometheus-prometheus.yaml    # 执行这条命令时
}

[root@kubeadm-master01 nfs-client]# kubectl apply -f prometheus-prometheus.yaml 
prometheus.monitoring.coreos.com/k8s created    # 显示没报错

但执行kubectl get pod -n monitoring时，没有出现如下两个pod
prometheus-k8s-0
prometheus-k8s-1

系统版本：CentOS Linux release 7.9.2009 (Core)
k8s版本：1.19.4
kube-prometheus版本：上周五git clone下来的版本

**Comment by veryrich** [comment]
我也是不生效 我是 1.20.4

**Comment by chinaboy007** [comment]
> 在kube-prometheus/manifests/add/nfs-client/install中
> persist(){
> kubectl apply -f grafana-pvc.yaml
> kubectl delete -f grafana-deployment.yaml
> kubectl apply -f grafana-deployment.yaml
> kubectl delete -f prometheus-prometheus.yaml
> kubectl apply -f prometheus-prometheus.yaml # 执行这条命令时
> }
> 
> [root@kubeadm-master01 nfs-client]# kubectl apply -f prometheus-prometheus.yaml
> prometheus.monitoring.coreos.com/k8s created # 显示没报错
> 
> 但执行kubectl get pod -n monitoring时，没有出现如下两个pod
> prometheus-k8s-0
> prometheus-k8s-1
> 
> 系统版本：CentOS Linux release 7.9.2009 (Core)
> k8s版本：1.19.4
> kube-prometheus版本：上周五git clone下来的版本

此BUG已解决，请重新下载安装包。或 修改install.sh 脚本，低68行，增加 cd ..

**Comment by chinaboy007** [comment]
> 我也是不生效 我是 1.20.4

此BUG已解决，请重新下载安装包。或 修改install.sh 脚本，低68行，增加 cd ..
